### ISSUE TITLE
textArea.scrollHeight has not the correct value at first run

### ISSUE THREAD

**Issue by stefan-beyer** [flivni/ionic2-autosize#3]
I think there should be a little timeout before 
`textArea.style.height = textArea.scrollHeight + "px";`
to give it a little time to recalculate the scrollHeight.

I did this:

```typescript
setTimeout(() => {
    textArea.style.height = textArea.scrollHeight + "px";
}, 100);
```

**Comment by zmbc** [comment]
Hi Stefan,

Can you provide some context? It's working fine for me as-is. How do I reproduce the issue?
